class CreateEpilepsies < ActiveRecord::Migration[5.2]
  def change
    create_table :epilepsies do |t|
      t.string :master_patient_id, null: false 
      t.string :srno 
      t.string :epi 
      t.string :surname 
      t.string :name 
      t.date :dob 
      t.string :sex 
      t.integer :mhh 
      t.string :phase2 
      t.string :phase2implant 
      t.string :phase2explant 
      t.string :phase2duration 
      t.string :phase2complications 
      t.string :side 
      t.string :resection 
      t.string :surgery_type 
      t.string :adult 
      t.string :rxn_date 
      t.string :additional_intervention 
      t.string :lastfu 
      t.integer :fu 
      t.string :week6_Engel 
      t.string :week6_ILAE 
      t.string :month6_Engel 
      t.string :month6_ILAE 
      t.string :year1_Engel 
      t.string :year1_ILAE 
      t.string :year2_Engel 
      t.string :year2_ILAE 
      t.string :year3_Engel 
      t.string :year3_ILAE 
      t.string :year4_Engel 
      t.string :year4_ILAE 
      t.string :year5_Engel 
      t.string :year5_ILAE 
      t.string :year10_Engel 
      t.string :year10_ILAE 
      t.string :year11_Engel 
      t.string :year11_ILAE 
      t.string :year12_Engel 
      t.string :year12_ILAE 
      t.string :year13_Engel 
      t.string :year13_ILAE 
      t.string :year14_Engel 
      t.string :year14_ILAE 
      t.string :year15_Engel 
      t.string :year15_ILAE 
      t.string :notes 
      t.string :engel 
      t.string :ilae 
      t.string :meds_at_fu 
      t.string :med_names 
      t.string :post_rxn_ecog 
      t.string :ecog_results 
      t.string :prior_neurosurgery 
      t.string :addNotes
      t.string :interictal_eeg
      t.string :ictal_eeg
      t.string :dominance 
      t.string :language_wada 
      t.string :memory_wada 
      t.string :wada_report_additional 
      t.string :meg 
      t.string :neuropsych_localization 
      t.string :viq 
      t.string :piq 
      t.string :fsiq 
      t.string :mri 
      t.string :pet 
      t.string :spect
      t.string :co_morbidities 
      t.string :etiology 
      t.string :pathology 
      t.string :outcome 
      t.string :post_op_neuropsych 
      t.string :viq1 
      t.string :piq1 
      t.string :fsiq1 
      t.string :overall_result
    end
  end
end
